"use strict";

export let checkoutDetailsHandler = {
  checkoutDetails: {
    currencySymbol: '',
    currencyCode: '',
    amount: '',
    token: '',
    fontFamily: {},
    ctaBorderRadius: 0,
    buttonColor: '#1CA672',
    buttonTextColor: 'white',
    headerColor: 'white',
    headerTextColor: '#363840',
    env: '',
    itemsLength: 0,
    errorMessage: '',
    shopperToken: null,
    isSuccessScreenVisible: false,
    isShippingAddressEnabled: false,
    isShippingAddressEditable: false,
    isFullNameEnabled: false,
    isFullNameEditable: false,
    isEmailEnabled: false,
    isEmailEditable: false,
    isPhoneEnabled: false,
    isPhoneEditable: false,
    isPanEnabled: false,
    isPanEditable: false,
    isDOBEnabled: false,
    isDOBEditable: false,
    isUpiIntentMethodEnabled: false,
    isUpiQRMethodEnabled: false,
    isUpiCollectMethodEnabled: false,
    isCardMethodEnabled: false,
    isWalletMethodEnabled: false,
    isNetBankingMethodEnabled: false,
    isEmiMethodEnabled: false,
    isBnplMethodEnabled: false,
    isUPIOtmIntentMethodEnabled: false,
    isUPIOtmCollectMethodEnabled: false,
    isUPIOtmQRMethodEnabled: false,
    isOrderItemDetailsVisible: true,
    isSICheckboxVisible: false,
    isSubscriptionCheckout: false
  }
};
export const setCheckoutDetailsHandler = handler => {
  checkoutDetailsHandler = handler;
};
export const setCheckOutDetailsHandlerToDefault = () => {
  checkoutDetailsHandler = {
    checkoutDetails: {
      currencySymbol: '',
      currencyCode: '',
      amount: '',
      token: '',
      fontFamily: {},
      ctaBorderRadius: 0,
      buttonColor: '',
      buttonTextColor: '',
      headerColor: '',
      headerTextColor: '',
      env: '',
      itemsLength: 0,
      errorMessage: '',
      shopperToken: null,
      isSuccessScreenVisible: false,
      isShippingAddressEnabled: false,
      isShippingAddressEditable: false,
      isFullNameEnabled: false,
      isFullNameEditable: false,
      isEmailEnabled: false,
      isEmailEditable: false,
      isPhoneEnabled: false,
      isPhoneEditable: false,
      isPanEnabled: false,
      isPanEditable: false,
      isDOBEnabled: false,
      isDOBEditable: false,
      isUpiIntentMethodEnabled: false,
      isUpiQRMethodEnabled: false,
      isUpiCollectMethodEnabled: false,
      isCardMethodEnabled: false,
      isWalletMethodEnabled: false,
      isNetBankingMethodEnabled: false,
      isEmiMethodEnabled: false,
      isBnplMethodEnabled: false,
      isUPIOtmIntentMethodEnabled: false,
      isUPIOtmCollectMethodEnabled: false,
      isUPIOtmQRMethodEnabled: false,
      isOrderItemDetailsVisible: true,
      isSICheckboxVisible: false,
      isSubscriptionCheckout: false
    }
  };
};
//# sourceMappingURL=checkoutDetailsHandler.js.map